version: '3.7'

services:

  nginx:
    image: nginx:1.16.1
    ports:
      - 80:80
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - auth-network
    depends_on:
      - php-fpm
      - composer

  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./public:/var/www/html
      - .:/var/www
    networks:
      - auth-network
    
    
  composer:
    image: composer:1.9.3
    command: install
    volumes:
      - .:/app
    networks:
      - auth-network

  mysql:
     image: mariadb:10.5.2
     ports:
       - 3306:3306
     volumes:
       - dbdata:/var/lib/mysql
     networks:
       - auth-network
     env_file:
       - mysql.env

networks:
  auth-network:
    driver: bridge

volumes:
  dbdata:
    driver: local